DA: true
autocast: true
batchsize: 8
block: 2
color_jitter: true
data_dir: ../../dataset/University-Release/train
droprate: 0.5
epochs: 200
erasing_p: 0.5
fname: train.txt
fp16: false
gpu_ids: '0'
h: 384
kl_loss: true
lr: 0.01
model: convnext_small_22k_224
name: DML
nclasses: 701
pad: 0
resnet: false
resume: false
sample_num: 1
share: true
steps:
- 80
- 120
train_all: true
triplet_loss: 0.3
views: 2
w: 384
warm_epoch: 0
